# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.response_list_transfer_response import ResponseListTransferResponse


class TestResponseListTransferResponse(unittest.TestCase):
    """ ResponseListTransferResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseListTransferResponse(self):
        """
        Test ResponseListTransferResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.response_list_transfer_response.ResponseListTransferResponse()
        pass


if __name__ == '__main__':
    unittest.main()
