# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.preauthorization_redsys_data import PreauthorizationRedsysData


class TestPreauthorizationRedsysData(unittest.TestCase):
    """ PreauthorizationRedsysData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreauthorizationRedsysData(self):
        """
        Test PreauthorizationRedsysData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.preauthorization_redsys_data.PreauthorizationRedsysData()
        pass


if __name__ == '__main__':
    unittest.main()
