# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.universal_pay_pay_by_web_response import UniversalPayPayByWebResponse


class TestUniversalPayPayByWebResponse(unittest.TestCase):
    """ UniversalPayPayByWebResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUniversalPayPayByWebResponse(self):
        """
        Test UniversalPayPayByWebResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.universal_pay_pay_by_web_response.UniversalPayPayByWebResponse()
        pass


if __name__ == '__main__':
    unittest.main()
