# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.redsys_preauthorize_by_web_post import RedsysPreauthorizeByWebPost


class TestRedsysPreauthorizeByWebPost(unittest.TestCase):
    """ RedsysPreauthorizeByWebPost unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedsysPreauthorizeByWebPost(self):
        """
        Test RedsysPreauthorizeByWebPost
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.redsys_preauthorize_by_web_post.RedsysPreauthorizeByWebPost()
        pass


if __name__ == '__main__':
    unittest.main()
