# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.refunds_api import RefundsApi


class TestRefundsApi(unittest.TestCase):
    """ RefundsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.refunds_api.RefundsApi()

    def tearDown(self):
        pass

    def test_refunds_refund_get(self):
        """
        Test case for refunds_refund_get

        View a Refund
        """
        pass


if __name__ == '__main__':
    unittest.main()
