# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.pay_outs_bankwire_api import PayOutsBankwireApi


class TestPayOutsBankwireApi(unittest.TestCase):
    """ PayOutsBankwireApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.pay_outs_bankwire_api.PayOutsBankwireApi()

    def tearDown(self):
        pass

    def test_pay_outs_bankwire_get(self):
        """
        Test case for pay_outs_bankwire_get

        
        """
        pass

    def test_pay_outs_bankwire_post(self):
        """
        Test case for pay_outs_bankwire_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
