# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.shipment_seur_api import ShipmentSeurApi


class TestShipmentSeurApi(unittest.TestCase):
    """ ShipmentSeurApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.shipment_seur_api.ShipmentSeurApi()

    def tearDown(self):
        pass

    def test_shipment_seur_seur_cancel_shipment(self):
        """
        Test case for shipment_seur_seur_cancel_shipment

        Cancels a shipment
        """
        pass

    def test_shipment_seur_seur_create_shipment(self):
        """
        Test case for shipment_seur_seur_create_shipment

        Creates a shipment
        """
        pass

    def test_shipment_seur_seur_get_shipment(self):
        """
        Test case for shipment_seur_seur_get_shipment

        Cancels a shipment
        """
        pass


if __name__ == '__main__':
    unittest.main()
