# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.universal_pay_token_request_post import UniversalPayTokenRequestPost


class TestUniversalPayTokenRequestPost(unittest.TestCase):
    """ UniversalPayTokenRequestPost unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUniversalPayTokenRequestPost(self):
        """
        Test UniversalPayTokenRequestPost
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.universal_pay_token_request_post.UniversalPayTokenRequestPost()
        pass


if __name__ == '__main__':
    unittest.main()
