# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.universal_pay_pay_by_web_post import UniversalPayPayByWebPost


class TestUniversalPayPayByWebPost(unittest.TestCase):
    """ UniversalPayPayByWebPost unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUniversalPayPayByWebPost(self):
        """
        Test UniversalPayPayByWebPost
        """
        model = swagger_client.models.universal_pay_pay_by_web_post.UniversalPayPayByWebPost()


if __name__ == '__main__':
    unittest.main()
