# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.universal_pay_tokenize_by_web_response import UniversalPayTokenizeByWebResponse


class TestUniversalPayTokenizeByWebResponse(unittest.TestCase):
    """ UniversalPayTokenizeByWebResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUniversalPayTokenizeByWebResponse(self):
        """
        Test UniversalPayTokenizeByWebResponse
        """
        model = swagger_client.models.universal_pay_tokenize_by_web_response.UniversalPayTokenizeByWebResponse()


if __name__ == '__main__':
    unittest.main()
