# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.address import Address
from .models.aplazame_order_item import AplazameOrderItem
from .models.aplazame_pay_by_web_post import AplazamePayByWebPost
from .models.aplazame_pay_ins_response import AplazamePayInsResponse
from .models.aplazame_refund_payment_post import AplazameRefundPaymentPost
from .models.aplazame_refund_response import AplazameRefundResponse
from .models.bank_account_ca_post import BankAccountCaPost
from .models.bank_account_gb_post import BankAccountGbPost
from .models.bank_account_iban_post import BankAccountIbanPost
from .models.bank_account_other_post import BankAccountOtherPost
from .models.bank_account_response import BankAccountResponse
from .models.bank_account_response_ca import BankAccountResponseCa
from .models.bank_account_response_gb import BankAccountResponseGb
from .models.bank_account_response_iban import BankAccountResponseIban
from .models.bank_account_response_other import BankAccountResponseOther
from .models.bank_account_response_us import BankAccountResponseUs
from .models.bank_account_us_post import BankAccountUsPost
from .models.card_put import CardPut
from .models.card_response import CardResponse
from .models.custom_api_error_response import CustomApiErrorResponse
from .models.customer import Customer
from .models.customer_detail import CustomerDetail
from .models.example_user_natural_post import ExampleUserNaturalPost
from .models.money import Money
from .models.pay_by_web_response import PayByWebResponse
from .models.pay_in_universal_token_request import PayInUniversalTokenRequest
from .models.pay_out_bank_wire_post import PayOutBankWirePost
from .models.pay_out_bank_wire_response import PayOutBankWireResponse
from .models.payment_redsys_data import PaymentRedsysData
from .models.payment_universal_pay_data import PaymentUniversalPayData
from .models.preauthorization_redsys_data import PreauthorizationRedsysData
from .models.product import Product
from .models.redsys_pay_by_web_post import RedsysPayByWebPost
from .models.redsys_pay_by_web_response import RedsysPayByWebResponse
from .models.redsys_pay_ins_response import RedsysPayInsResponse
from .models.redsys_preauthorization_cancellation_post import RedsysPreauthorizationCancellationPost
from .models.redsys_preauthorization_cancellation_response import RedsysPreauthorizationCancellationResponse
from .models.redsys_preauthorization_confirmation_post import RedsysPreauthorizationConfirmationPost
from .models.redsys_preauthorization_confirmation_response import RedsysPreauthorizationConfirmationResponse
from .models.redsys_preauthorize_by_web_post import RedsysPreauthorizeByWebPost
from .models.redsys_preauthorize_by_web_response import RedsysPreauthorizeByWebResponse
from .models.redsys_preauthorize_response import RedsysPreauthorizeResponse
from .models.redsys_refund_post import RedsysRefundPost
from .models.redsys_refund_response import RedsysRefundResponse
from .models.refund_reason import RefundReason
from .models.refund_redsys_data import RefundRedsysData
from .models.response_list_card_response import ResponseListCardResponse
from .models.response_list_transfer_response import ResponseListTransferResponse
from .models.response_list_wallet_response import ResponseListWalletResponse
from .models.seur_shipment_cancellation_response import SeurShipmentCancellationResponse
from .models.seur_shipment_post import SeurShipmentPost
from .models.seur_shipment_response import SeurShipmentResponse
from .models.shipment_actor import ShipmentActor
from .models.telephone import Telephone
from .models.telephone_seur import TelephoneSeur
from .models.transaction_response import TransactionResponse
from .models.transfer_post import TransferPost
from .models.transfer_response import TransferResponse
from .models.universal_pay_pay_by_web_post import UniversalPayPayByWebPost
from .models.universal_pay_pay_by_web_response import UniversalPayPayByWebResponse
from .models.universal_pay_pay_ins_response import UniversalPayPayInsResponse
from .models.universal_pay_refund_post import UniversalPayRefundPost
from .models.universal_pay_refund_response import UniversalPayRefundResponse
from .models.universal_pay_token_request_post import UniversalPayTokenRequestPost
from .models.user_legal_post import UserLegalPost
from .models.user_legal_put import UserLegalPut
from .models.user_legal_response import UserLegalResponse
from .models.user_natural_post import UserNaturalPost
from .models.user_natural_put import UserNaturalPut
from .models.user_natural_response import UserNaturalResponse
from .models.user_response import UserResponse
from .models.wallet_post import WalletPost
from .models.wallet_put import WalletPut
from .models.wallet_response import WalletResponse

# import apis into sdk package
from .apis.cards_api import CardsApi
from .apis.pay_ins_aplazame_api import PayInsAplazameApi
from .apis.pay_ins_redsys_api import PayInsRedsysApi
from .apis.pay_ins_universal_pay_api import PayInsUniversalPayApi
from .apis.pay_outs_api import PayOutsApi
from .apis.refunds_api import RefundsApi
from .apis.shipment_seur_api import ShipmentSeurApi
from .apis.transfers_api import TransfersApi
from .apis.users_api import UsersApi
from .apis.wallets_api import WalletsApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
