# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PayByWebResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, pay_in_id=None, checkout_data=None):
        """
        PayByWebResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'pay_in_id': 'str',
            'checkout_data': 'str'
        }

        self.attribute_map = {
            'pay_in_id': 'PayInId',
            'checkout_data': 'CheckoutData'
        }

        self._pay_in_id = pay_in_id
        self._checkout_data = checkout_data

    @property
    def pay_in_id(self):
        """
        Gets the pay_in_id of this PayByWebResponse.
        Id of the payment

        :return: The pay_in_id of this PayByWebResponse.
        :rtype: str
        """
        return self._pay_in_id

    @pay_in_id.setter
    def pay_in_id(self, pay_in_id):
        """
        Sets the pay_in_id of this PayByWebResponse.
        Id of the payment

        :param pay_in_id: The pay_in_id of this PayByWebResponse.
        :type: str
        """

        self._pay_in_id = pay_in_id

    @property
    def checkout_data(self):
        """
        Gets the checkout_data of this PayByWebResponse.

        :return: The checkout_data of this PayByWebResponse.
        :rtype: str
        """
        return self._checkout_data

    @checkout_data.setter
    def checkout_data(self, checkout_data):
        """
        Sets the checkout_data of this PayByWebResponse.

        :param checkout_data: The checkout_data of this PayByWebResponse.
        :type: str
        """

        self._checkout_data = checkout_data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PayByWebResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
