# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PayOutBankwirePost(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, tag=None, debited_funds=None, fees=None, bank_account_id=None, debited_wallet_id=None, bank_wire_ref=None):
        """
        PayOutBankwirePost - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'tag': 'str',
            'debited_funds': 'Money',
            'fees': 'Money',
            'bank_account_id': 'str',
            'debited_wallet_id': 'str',
            'bank_wire_ref': 'str'
        }

        self.attribute_map = {
            'tag': 'Tag',
            'debited_funds': 'DebitedFunds',
            'fees': 'Fees',
            'bank_account_id': 'BankAccountId',
            'debited_wallet_id': 'DebitedWalletId',
            'bank_wire_ref': 'BankWireRef'
        }

        self._tag = tag
        self._debited_funds = debited_funds
        self._fees = fees
        self._bank_account_id = bank_account_id
        self._debited_wallet_id = debited_wallet_id
        self._bank_wire_ref = bank_wire_ref

    @property
    def tag(self):
        """
        Gets the tag of this PayOutBankwirePost.

        :return: The tag of this PayOutBankwirePost.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """
        Sets the tag of this PayOutBankwirePost.

        :param tag: The tag of this PayOutBankwirePost.
        :type: str
        """

        self._tag = tag

    @property
    def debited_funds(self):
        """
        Gets the debited_funds of this PayOutBankwirePost.

        :return: The debited_funds of this PayOutBankwirePost.
        :rtype: Money
        """
        return self._debited_funds

    @debited_funds.setter
    def debited_funds(self, debited_funds):
        """
        Sets the debited_funds of this PayOutBankwirePost.

        :param debited_funds: The debited_funds of this PayOutBankwirePost.
        :type: Money
        """

        self._debited_funds = debited_funds

    @property
    def fees(self):
        """
        Gets the fees of this PayOutBankwirePost.

        :return: The fees of this PayOutBankwirePost.
        :rtype: Money
        """
        return self._fees

    @fees.setter
    def fees(self, fees):
        """
        Sets the fees of this PayOutBankwirePost.

        :param fees: The fees of this PayOutBankwirePost.
        :type: Money
        """

        self._fees = fees

    @property
    def bank_account_id(self):
        """
        Gets the bank_account_id of this PayOutBankwirePost.

        :return: The bank_account_id of this PayOutBankwirePost.
        :rtype: str
        """
        return self._bank_account_id

    @bank_account_id.setter
    def bank_account_id(self, bank_account_id):
        """
        Sets the bank_account_id of this PayOutBankwirePost.

        :param bank_account_id: The bank_account_id of this PayOutBankwirePost.
        :type: str
        """

        self._bank_account_id = bank_account_id

    @property
    def debited_wallet_id(self):
        """
        Gets the debited_wallet_id of this PayOutBankwirePost.

        :return: The debited_wallet_id of this PayOutBankwirePost.
        :rtype: str
        """
        return self._debited_wallet_id

    @debited_wallet_id.setter
    def debited_wallet_id(self, debited_wallet_id):
        """
        Sets the debited_wallet_id of this PayOutBankwirePost.

        :param debited_wallet_id: The debited_wallet_id of this PayOutBankwirePost.
        :type: str
        """

        self._debited_wallet_id = debited_wallet_id

    @property
    def bank_wire_ref(self):
        """
        Gets the bank_wire_ref of this PayOutBankwirePost.

        :return: The bank_wire_ref of this PayOutBankwirePost.
        :rtype: str
        """
        return self._bank_wire_ref

    @bank_wire_ref.setter
    def bank_wire_ref(self, bank_wire_ref):
        """
        Sets the bank_wire_ref of this PayOutBankwirePost.

        :param bank_wire_ref: The bank_wire_ref of this PayOutBankwirePost.
        :type: str
        """

        self._bank_wire_ref = bank_wire_ref

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PayOutBankwirePost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
