# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RefundReason(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, message=None):
        """
        RefundReason - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'str',
            'message': 'str'
        }

        self.attribute_map = {
            'type': 'Type',
            'message': 'Message'
        }

        self._type = type
        self._message = message

    @property
    def type(self):
        """
        Gets the type of this RefundReason.
        The type of reason for refusal

        :return: The type of this RefundReason.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this RefundReason.
        The type of reason for refusal

        :param type: The type of this RefundReason.
        :type: str
        """
        allowed_values = ["NotSpecified", "BANKACCOUNT_INCORRECT", "BANKACCOUNT_HAS_BEEN_CLOSED", "OWNER_DOT_NOT_MATCH_BANKACCOUNT", "WITHDRAWAL_IMPOSSIBLE_ON_SAVINGS_ACCOUNTS", "INITIALIZED_BY_CLIENT", "OTHER"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def message(self):
        """
        Gets the message of this RefundReason.
        The message accompanying a refusal

        :return: The message of this RefundReason.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this RefundReason.
        The message accompanying a refusal

        :param message: The message of this RefundReason.
        :type: str
        """

        self._message = message

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RefundReason):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
