# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ResponseListWalletResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'values': 'list[WalletResponse]',
        'total': 'int'
    }

    attribute_map = {
        'values': 'Values',
        'total': 'Total'
    }

    def __init__(self, values=None, total=None):
        """
        ResponseListWalletResponse - a model defined in Swagger
        """

        self._values = None
        self._total = None

        if values is not None:
          self.values = values
        if total is not None:
          self.total = total

    @property
    def values(self):
        """
        Gets the values of this ResponseListWalletResponse.

        :return: The values of this ResponseListWalletResponse.
        :rtype: list[WalletResponse]
        """
        return self._values

    @values.setter
    def values(self, values):
        """
        Sets the values of this ResponseListWalletResponse.

        :param values: The values of this ResponseListWalletResponse.
        :type: list[WalletResponse]
        """

        self._values = values

    @property
    def total(self):
        """
        Gets the total of this ResponseListWalletResponse.

        :return: The total of this ResponseListWalletResponse.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this ResponseListWalletResponse.

        :param total: The total of this ResponseListWalletResponse.
        :type: int
        """

        self._total = total

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ResponseListWalletResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
