# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ShipmentActor(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, telephone=None, address=None):
        """
        ShipmentActor - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'telephone': 'TelephoneSeur',
            'address': 'Address'
        }

        self.attribute_map = {
            'name': 'Name',
            'telephone': 'Telephone',
            'address': 'Address'
        }

        self._name = name
        self._telephone = telephone
        self._address = address

    @property
    def name(self):
        """
        Gets the name of this ShipmentActor.

        :return: The name of this ShipmentActor.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ShipmentActor.

        :param name: The name of this ShipmentActor.
        :type: str
        """

        self._name = name

    @property
    def telephone(self):
        """
        Gets the telephone of this ShipmentActor.

        :return: The telephone of this ShipmentActor.
        :rtype: TelephoneSeur
        """
        return self._telephone

    @telephone.setter
    def telephone(self, telephone):
        """
        Sets the telephone of this ShipmentActor.

        :param telephone: The telephone of this ShipmentActor.
        :type: TelephoneSeur
        """

        self._telephone = telephone

    @property
    def address(self):
        """
        Gets the address of this ShipmentActor.

        :return: The address of this ShipmentActor.
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address):
        """
        Sets the address of this ShipmentActor.

        :param address: The address of this ShipmentActor.
        :type: Address
        """

        self._address = address

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ShipmentActor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
