# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TransferResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, debited_funds=None, credited_funds=None, fees=None, debited_wallet_id=None, credited_wallet_id=None, author_id=None, credited_user_id=None, nature=None, status=None, execution_date=None, result_code=None, result_message=None, type=None, id=None, creation_date=None, tag=None):
        """
        TransferResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'debited_funds': 'Money',
            'credited_funds': 'Money',
            'fees': 'Money',
            'debited_wallet_id': 'str',
            'credited_wallet_id': 'str',
            'author_id': 'str',
            'credited_user_id': 'str',
            'nature': 'str',
            'status': 'str',
            'execution_date': 'int',
            'result_code': 'str',
            'result_message': 'str',
            'type': 'str',
            'id': 'str',
            'creation_date': 'int',
            'tag': 'str'
        }

        self.attribute_map = {
            'debited_funds': 'DebitedFunds',
            'credited_funds': 'CreditedFunds',
            'fees': 'Fees',
            'debited_wallet_id': 'DebitedWalletId',
            'credited_wallet_id': 'CreditedWalletId',
            'author_id': 'AuthorId',
            'credited_user_id': 'CreditedUserId',
            'nature': 'Nature',
            'status': 'Status',
            'execution_date': 'ExecutionDate',
            'result_code': 'ResultCode',
            'result_message': 'ResultMessage',
            'type': 'Type',
            'id': 'Id',
            'creation_date': 'CreationDate',
            'tag': 'Tag'
        }

        self._debited_funds = debited_funds
        self._credited_funds = credited_funds
        self._fees = fees
        self._debited_wallet_id = debited_wallet_id
        self._credited_wallet_id = credited_wallet_id
        self._author_id = author_id
        self._credited_user_id = credited_user_id
        self._nature = nature
        self._status = status
        self._execution_date = execution_date
        self._result_code = result_code
        self._result_message = result_message
        self._type = type
        self._id = id
        self._creation_date = creation_date
        self._tag = tag

    @property
    def debited_funds(self):
        """
        Gets the debited_funds of this TransferResponse.
        Information about the funds that are being debited

        :return: The debited_funds of this TransferResponse.
        :rtype: Money
        """
        return self._debited_funds

    @debited_funds.setter
    def debited_funds(self, debited_funds):
        """
        Sets the debited_funds of this TransferResponse.
        Information about the funds that are being debited

        :param debited_funds: The debited_funds of this TransferResponse.
        :type: Money
        """

        self._debited_funds = debited_funds

    @property
    def credited_funds(self):
        """
        Gets the credited_funds of this TransferResponse.
        Details about the funds that are being credited (DebitedFunds – Fees = CreditedFunds)

        :return: The credited_funds of this TransferResponse.
        :rtype: Money
        """
        return self._credited_funds

    @credited_funds.setter
    def credited_funds(self, credited_funds):
        """
        Sets the credited_funds of this TransferResponse.
        Details about the funds that are being credited (DebitedFunds – Fees = CreditedFunds)

        :param credited_funds: The credited_funds of this TransferResponse.
        :type: Money
        """

        self._credited_funds = credited_funds

    @property
    def fees(self):
        """
        Gets the fees of this TransferResponse.
        Information about the fees that were taken by the client for this transaction (and were hence transferred to the Client's platform wallet)

        :return: The fees of this TransferResponse.
        :rtype: Money
        """
        return self._fees

    @fees.setter
    def fees(self, fees):
        """
        Sets the fees of this TransferResponse.
        Information about the fees that were taken by the client for this transaction (and were hence transferred to the Client's platform wallet)

        :param fees: The fees of this TransferResponse.
        :type: Money
        """

        self._fees = fees

    @property
    def debited_wallet_id(self):
        """
        Gets the debited_wallet_id of this TransferResponse.
        The ID of the wallet that was debited

        :return: The debited_wallet_id of this TransferResponse.
        :rtype: str
        """
        return self._debited_wallet_id

    @debited_wallet_id.setter
    def debited_wallet_id(self, debited_wallet_id):
        """
        Sets the debited_wallet_id of this TransferResponse.
        The ID of the wallet that was debited

        :param debited_wallet_id: The debited_wallet_id of this TransferResponse.
        :type: str
        """

        self._debited_wallet_id = debited_wallet_id

    @property
    def credited_wallet_id(self):
        """
        Gets the credited_wallet_id of this TransferResponse.
        The ID of the wallet where money will be credited

        :return: The credited_wallet_id of this TransferResponse.
        :rtype: str
        """
        return self._credited_wallet_id

    @credited_wallet_id.setter
    def credited_wallet_id(self, credited_wallet_id):
        """
        Sets the credited_wallet_id of this TransferResponse.
        The ID of the wallet where money will be credited

        :param credited_wallet_id: The credited_wallet_id of this TransferResponse.
        :type: str
        """

        self._credited_wallet_id = credited_wallet_id

    @property
    def author_id(self):
        """
        Gets the author_id of this TransferResponse.
        A user's ID

        :return: The author_id of this TransferResponse.
        :rtype: str
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id):
        """
        Sets the author_id of this TransferResponse.
        A user's ID

        :param author_id: The author_id of this TransferResponse.
        :type: str
        """

        self._author_id = author_id

    @property
    def credited_user_id(self):
        """
        Gets the credited_user_id of this TransferResponse.
        The user ID who was credited

        :return: The credited_user_id of this TransferResponse.
        :rtype: str
        """
        return self._credited_user_id

    @credited_user_id.setter
    def credited_user_id(self, credited_user_id):
        """
        Sets the credited_user_id of this TransferResponse.
        The user ID who was credited

        :param credited_user_id: The credited_user_id of this TransferResponse.
        :type: str
        """

        self._credited_user_id = credited_user_id

    @property
    def nature(self):
        """
        Gets the nature of this TransferResponse.
        The nature of the transaction

        :return: The nature of this TransferResponse.
        :rtype: str
        """
        return self._nature

    @nature.setter
    def nature(self, nature):
        """
        Sets the nature of this TransferResponse.
        The nature of the transaction

        :param nature: The nature of this TransferResponse.
        :type: str
        """
        allowed_values = ["REGULAR", "REFUND", "REPUDIATION", "SETTLEMENT"]
        if nature not in allowed_values:
            raise ValueError(
                "Invalid value for `nature` ({0}), must be one of {1}"
                .format(nature, allowed_values)
            )

        self._nature = nature

    @property
    def status(self):
        """
        Gets the status of this TransferResponse.
        The status of the transaction

        :return: The status of this TransferResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this TransferResponse.
        The status of the transaction

        :param status: The status of this TransferResponse.
        :type: str
        """
        allowed_values = ["CREATED", "SUCCEEDED", "FAILED"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def execution_date(self):
        """
        Gets the execution_date of this TransferResponse.
        When the transaction happened

        :return: The execution_date of this TransferResponse.
        :rtype: int
        """
        return self._execution_date

    @execution_date.setter
    def execution_date(self, execution_date):
        """
        Sets the execution_date of this TransferResponse.
        When the transaction happened

        :param execution_date: The execution_date of this TransferResponse.
        :type: int
        """

        self._execution_date = execution_date

    @property
    def result_code(self):
        """
        Gets the result_code of this TransferResponse.
        The result code

        :return: The result_code of this TransferResponse.
        :rtype: str
        """
        return self._result_code

    @result_code.setter
    def result_code(self, result_code):
        """
        Sets the result_code of this TransferResponse.
        The result code

        :param result_code: The result_code of this TransferResponse.
        :type: str
        """

        self._result_code = result_code

    @property
    def result_message(self):
        """
        Gets the result_message of this TransferResponse.
        A verbal explanation of the ResultCode

        :return: The result_message of this TransferResponse.
        :rtype: str
        """
        return self._result_message

    @result_message.setter
    def result_message(self, result_message):
        """
        Sets the result_message of this TransferResponse.
        A verbal explanation of the ResultCode

        :param result_message: The result_message of this TransferResponse.
        :type: str
        """

        self._result_message = result_message

    @property
    def type(self):
        """
        Gets the type of this TransferResponse.
        The type of the transaction

        :return: The type of this TransferResponse.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this TransferResponse.
        The type of the transaction

        :param type: The type of this TransferResponse.
        :type: str
        """
        allowed_values = ["PAYIN", "PAYOUT", "TRANSFER"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def id(self):
        """
        Gets the id of this TransferResponse.

        :return: The id of this TransferResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TransferResponse.

        :param id: The id of this TransferResponse.
        :type: str
        """

        self._id = id

    @property
    def creation_date(self):
        """
        Gets the creation_date of this TransferResponse.

        :return: The creation_date of this TransferResponse.
        :rtype: int
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """
        Sets the creation_date of this TransferResponse.

        :param creation_date: The creation_date of this TransferResponse.
        :type: int
        """

        self._creation_date = creation_date

    @property
    def tag(self):
        """
        Gets the tag of this TransferResponse.

        :return: The tag of this TransferResponse.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """
        Sets the tag of this TransferResponse.

        :param tag: The tag of this TransferResponse.
        :type: str
        """

        self._tag = tag

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TransferResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
