# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UniversalPayPayByWebPost(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, debited_funds=None, fees=None, card_id=None, save_card=None, statement_descriptor=None, tag=None, credited_wallet_id=None, secure_mode=None, success_url=None, cancel_url=None, language=None, customer=None):
        """
        UniversalPayPayByWebPost - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'debited_funds': 'Money',
            'fees': 'Money',
            'card_id': 'str',
            'save_card': 'bool',
            'statement_descriptor': 'str',
            'tag': 'str',
            'credited_wallet_id': 'str',
            'secure_mode': 'str',
            'success_url': 'str',
            'cancel_url': 'str',
            'language': 'str',
            'customer': 'CustomerDetail'
        }

        self.attribute_map = {
            'debited_funds': 'DebitedFunds',
            'fees': 'Fees',
            'card_id': 'CardId',
            'save_card': 'SaveCard',
            'statement_descriptor': 'StatementDescriptor',
            'tag': 'Tag',
            'credited_wallet_id': 'CreditedWalletId',
            'secure_mode': 'SecureMode',
            'success_url': 'SuccessUrl',
            'cancel_url': 'CancelUrl',
            'language': 'Language',
            'customer': 'Customer'
        }

        self._debited_funds = debited_funds
        self._fees = fees
        self._card_id = card_id
        self._save_card = save_card
        self._statement_descriptor = statement_descriptor
        self._tag = tag
        self._credited_wallet_id = credited_wallet_id
        self._secure_mode = secure_mode
        self._success_url = success_url
        self._cancel_url = cancel_url
        self._language = language
        self._customer = customer

    @property
    def debited_funds(self):
        """
        Gets the debited_funds of this UniversalPayPayByWebPost.
        Information about the funds that are being debited

        :return: The debited_funds of this UniversalPayPayByWebPost.
        :rtype: Money
        """
        return self._debited_funds

    @debited_funds.setter
    def debited_funds(self, debited_funds):
        """
        Sets the debited_funds of this UniversalPayPayByWebPost.
        Information about the funds that are being debited

        :param debited_funds: The debited_funds of this UniversalPayPayByWebPost.
        :type: Money
        """
        if debited_funds is None:
            raise ValueError("Invalid value for `debited_funds`, must not be `None`")

        self._debited_funds = debited_funds

    @property
    def fees(self):
        """
        Gets the fees of this UniversalPayPayByWebPost.
        Information about the fees that were taken by the client for this transaction (and were hence transferred to the Client's platform wallet)

        :return: The fees of this UniversalPayPayByWebPost.
        :rtype: Money
        """
        return self._fees

    @fees.setter
    def fees(self, fees):
        """
        Sets the fees of this UniversalPayPayByWebPost.
        Information about the fees that were taken by the client for this transaction (and were hence transferred to the Client's platform wallet)

        :param fees: The fees of this UniversalPayPayByWebPost.
        :type: Money
        """
        if fees is None:
            raise ValueError("Invalid value for `fees`, must not be `None`")

        self._fees = fees

    @property
    def card_id(self):
        """
        Gets the card_id of this UniversalPayPayByWebPost.

        :return: The card_id of this UniversalPayPayByWebPost.
        :rtype: str
        """
        return self._card_id

    @card_id.setter
    def card_id(self, card_id):
        """
        Sets the card_id of this UniversalPayPayByWebPost.

        :param card_id: The card_id of this UniversalPayPayByWebPost.
        :type: str
        """

        self._card_id = card_id

    @property
    def save_card(self):
        """
        Gets the save_card of this UniversalPayPayByWebPost.

        :return: The save_card of this UniversalPayPayByWebPost.
        :rtype: bool
        """
        return self._save_card

    @save_card.setter
    def save_card(self, save_card):
        """
        Sets the save_card of this UniversalPayPayByWebPost.

        :param save_card: The save_card of this UniversalPayPayByWebPost.
        :type: bool
        """

        self._save_card = save_card

    @property
    def statement_descriptor(self):
        """
        Gets the statement_descriptor of this UniversalPayPayByWebPost.

        :return: The statement_descriptor of this UniversalPayPayByWebPost.
        :rtype: str
        """
        return self._statement_descriptor

    @statement_descriptor.setter
    def statement_descriptor(self, statement_descriptor):
        """
        Sets the statement_descriptor of this UniversalPayPayByWebPost.

        :param statement_descriptor: The statement_descriptor of this UniversalPayPayByWebPost.
        :type: str
        """
        if statement_descriptor is None:
            raise ValueError("Invalid value for `statement_descriptor`, must not be `None`")

        self._statement_descriptor = statement_descriptor

    @property
    def tag(self):
        """
        Gets the tag of this UniversalPayPayByWebPost.
        Custom data that you can add to this item

        :return: The tag of this UniversalPayPayByWebPost.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """
        Sets the tag of this UniversalPayPayByWebPost.
        Custom data that you can add to this item

        :param tag: The tag of this UniversalPayPayByWebPost.
        :type: str
        """

        self._tag = tag

    @property
    def credited_wallet_id(self):
        """
        Gets the credited_wallet_id of this UniversalPayPayByWebPost.
        The ID of the wallet where money will be credited

        :return: The credited_wallet_id of this UniversalPayPayByWebPost.
        :rtype: str
        """
        return self._credited_wallet_id

    @credited_wallet_id.setter
    def credited_wallet_id(self, credited_wallet_id):
        """
        Sets the credited_wallet_id of this UniversalPayPayByWebPost.
        The ID of the wallet where money will be credited

        :param credited_wallet_id: The credited_wallet_id of this UniversalPayPayByWebPost.
        :type: str
        """
        if credited_wallet_id is None:
            raise ValueError("Invalid value for `credited_wallet_id`, must not be `None`")

        self._credited_wallet_id = credited_wallet_id

    @property
    def secure_mode(self):
        """
        Gets the secure_mode of this UniversalPayPayByWebPost.

        :return: The secure_mode of this UniversalPayPayByWebPost.
        :rtype: str
        """
        return self._secure_mode

    @secure_mode.setter
    def secure_mode(self, secure_mode):
        """
        Sets the secure_mode of this UniversalPayPayByWebPost.

        :param secure_mode: The secure_mode of this UniversalPayPayByWebPost.
        :type: str
        """
        allowed_values = ["NotSpecified", "DEFAULT", "FORCE"]
        if secure_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `secure_mode` ({0}), must be one of {1}"
                .format(secure_mode, allowed_values)
            )

        self._secure_mode = secure_mode

    @property
    def success_url(self):
        """
        Gets the success_url of this UniversalPayPayByWebPost.
        Url to redirect the browser in case the payment is completed successfully

        :return: The success_url of this UniversalPayPayByWebPost.
        :rtype: str
        """
        return self._success_url

    @success_url.setter
    def success_url(self, success_url):
        """
        Sets the success_url of this UniversalPayPayByWebPost.
        Url to redirect the browser in case the payment is completed successfully

        :param success_url: The success_url of this UniversalPayPayByWebPost.
        :type: str
        """

        self._success_url = success_url

    @property
    def cancel_url(self):
        """
        Gets the cancel_url of this UniversalPayPayByWebPost.
        Url to redirect the browser in case the payment is not completed successfully

        :return: The cancel_url of this UniversalPayPayByWebPost.
        :rtype: str
        """
        return self._cancel_url

    @cancel_url.setter
    def cancel_url(self, cancel_url):
        """
        Sets the cancel_url of this UniversalPayPayByWebPost.
        Url to redirect the browser in case the payment is not completed successfully

        :param cancel_url: The cancel_url of this UniversalPayPayByWebPost.
        :type: str
        """

        self._cancel_url = cancel_url

    @property
    def language(self):
        """
        Gets the language of this UniversalPayPayByWebPost.
        Valid values are ES, EN, FR

        :return: The language of this UniversalPayPayByWebPost.
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """
        Sets the language of this UniversalPayPayByWebPost.
        Valid values are ES, EN, FR

        :param language: The language of this UniversalPayPayByWebPost.
        :type: str
        """
        allowed_values = ["NotSpecified", "DE", "EN", "DA", "ES", "ET", "FI", "FR", "EL", "HU", "IT", "NL", "NO", "PL", "PT", "SK", "SV", "CS"]
        if language not in allowed_values:
            raise ValueError(
                "Invalid value for `language` ({0}), must be one of {1}"
                .format(language, allowed_values)
            )

        self._language = language

    @property
    def customer(self):
        """
        Gets the customer of this UniversalPayPayByWebPost.

        :return: The customer of this UniversalPayPayByWebPost.
        :rtype: CustomerDetail
        """
        return self._customer

    @customer.setter
    def customer(self, customer):
        """
        Sets the customer of this UniversalPayPayByWebPost.

        :param customer: The customer of this UniversalPayPayByWebPost.
        :type: CustomerDetail
        """
        if customer is None:
            raise ValueError("Invalid value for `customer`, must not be `None`")

        self._customer = customer

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UniversalPayPayByWebPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
