# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class PayInsAplazameApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def pay_ins_aplazame_aplazame_get_payment(self, pay_in_id, **kwargs):
        """
        -------
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.pay_ins_aplazame_aplazame_get_payment(pay_in_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str pay_in_id: ------ (required)
        :return: AplazamePayInsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.pay_ins_aplazame_aplazame_get_payment_with_http_info(pay_in_id, **kwargs)
        else:
            (data) = self.pay_ins_aplazame_aplazame_get_payment_with_http_info(pay_in_id, **kwargs)
            return data

    def pay_ins_aplazame_aplazame_get_payment_with_http_info(self, pay_in_id, **kwargs):
        """
        -------
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.pay_ins_aplazame_aplazame_get_payment_with_http_info(pay_in_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str pay_in_id: ------ (required)
        :return: AplazamePayInsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['pay_in_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method pay_ins_aplazame_aplazame_get_payment" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'pay_in_id' is set
        if ('pay_in_id' not in params) or (params['pay_in_id'] is None):
            raise ValueError("Missing the required parameter `pay_in_id` when calling `pay_ins_aplazame_aplazame_get_payment`")


        collection_formats = {}

        resource_path = '/v2.01/PayInsAplazame/payments/{PayInId}'.replace('{format}', 'json')
        path_params = {}
        if 'pay_in_id' in params:
            path_params['PayInId'] = params['pay_in_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['text/plain', 'application/json', 'text/json'])

        # Authentication setting
        auth_settings = ['oauth2']

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AplazamePayInsResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def pay_ins_aplazame_aplazame_post_payment_by_web(self, **kwargs):
        """
        --------
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.pay_ins_aplazame_aplazame_post_payment_by_web(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param AplazamePayByWebPost aplazame_pay_in: ------------
        :return: PayByWebResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.pay_ins_aplazame_aplazame_post_payment_by_web_with_http_info(**kwargs)
        else:
            (data) = self.pay_ins_aplazame_aplazame_post_payment_by_web_with_http_info(**kwargs)
            return data

    def pay_ins_aplazame_aplazame_post_payment_by_web_with_http_info(self, **kwargs):
        """
        --------
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.pay_ins_aplazame_aplazame_post_payment_by_web_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param AplazamePayByWebPost aplazame_pay_in: ------------
        :return: PayByWebResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['aplazame_pay_in']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method pay_ins_aplazame_aplazame_post_payment_by_web" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        resource_path = '/v2.01/PayInsAplazame/payments/web'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'aplazame_pay_in' in params:
            body_params = params['aplazame_pay_in']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['text/plain', 'application/json', 'text/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json', 'text/json', 'application/json-patch+json'])

        # Authentication setting
        auth_settings = ['oauth2']

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='PayByWebResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def pay_ins_aplazame_refund(self, pay_in_id, **kwargs):
        """
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.pay_ins_aplazame_refund(pay_in_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str pay_in_id: (required)
        :param AplazameRefundPaymentPost aplazame_refund:
        :return: AplazameRefundResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.pay_ins_aplazame_refund_with_http_info(pay_in_id, **kwargs)
        else:
            (data) = self.pay_ins_aplazame_refund_with_http_info(pay_in_id, **kwargs)
            return data

    def pay_ins_aplazame_refund_with_http_info(self, pay_in_id, **kwargs):
        """
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.pay_ins_aplazame_refund_with_http_info(pay_in_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str pay_in_id: (required)
        :param AplazameRefundPaymentPost aplazame_refund:
        :return: AplazameRefundResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['pay_in_id', 'aplazame_refund']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method pay_ins_aplazame_refund" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'pay_in_id' is set
        if ('pay_in_id' not in params) or (params['pay_in_id'] is None):
            raise ValueError("Missing the required parameter `pay_in_id` when calling `pay_ins_aplazame_refund`")


        collection_formats = {}

        resource_path = '/v2.01/PayInsAplazame/payments/{PayInId}/refunds'.replace('{format}', 'json')
        path_params = {}
        if 'pay_in_id' in params:
            path_params['PayInId'] = params['pay_in_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'aplazame_refund' in params:
            body_params = params['aplazame_refund']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['text/plain', 'application/json', 'text/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json', 'text/json', 'application/json-patch+json'])

        # Authentication setting
        auth_settings = ['oauth2']

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AplazameRefundResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
